tools:
    php_sim: false
    php_pdepend: true
    php_analyzer: true
    php_code_coverage: true
    external_code_coverage: false

build:
    nodes:
        php70:
            environment:
                postgresql: false
                redis: false
                php:
                    version: 7.0.33
                    ini:
                        xdebug.mode: coverage
            tests:
                override:
                    -
                        command: 'vendor/phpunit/phpunit/phpunit --coverage-clover=tests/cover/coverage.xml'
                        coverage:
                            file: 'tests/cover/coverage.xml'
                            format: clover
        php71:
            environment:
                postgresql: false
                redis: false
                php:
                    version: 7.1.25
            tests:
                override:
                    -
                        command: 'vendor/phpunit/phpunit/phpunit --coverage-clover=tests/cover/coverage.xml'
                        coverage:
                            file: 'tests/cover/coverage.xml'
                            format: clover
        php72:
            environment:
                postgresql: false
                redis: false
                php:
                    version: 7.2.13
            tests:
                override:
                    -
                        command: 'vendor/phpunit/phpunit/phpunit --coverage-clover=tests/cover/coverage.xml'
                        coverage:
                            file: 'tests/cover/coverage.xml'
                            format: clover
        php73:
            environment:
                postgresql: false
                redis: false
                php:
                    version: 7.3.0
            tests:
                override:
                    -
                        command: 'vendor/phpunit/phpunit/phpunit --coverage-clover=tests/cover/coverage.xml'
                        coverage:
                            file: 'tests/cover/coverage.xml'
                            format: clover

    environment:
        postgresql: false
        redis: false
        php:
            version: 7.3
    tests:
        override:
            -
                command: 'vendor/phpunit/phpunit/phpunit --coverage-clover=tests/cover/coverage.xml'
                coverage:
                    file: 'tests/cover/coverage.xml'
                    format: clover

filter:
    excluded_paths: [vendor/*, tests/*, examples/*]