<?php

namespace sokolnikov911\YandexTurboPages\helpers;

require_once dirname(__DIR__) . '/vendor/autoload.php';


// Content generated by Content helper can be used in turboContent method in any Item


// generate header
$menuArray = [
    ['url' => 'http://example/page1.html', 'title' => 'Page title 1'],
    ['url' => 'http://example/page2.html', 'title' => 'Page title 2']
];
$header = Content::header('Main title', 'Second title',
    'http://example.com/image1.jpg', 'Image description', $menuArray);



// generate comments block
$commentsArray = [
    [
        'author' => 'First Author Name',
        'avatar' => 'http://example.com/user1.jpg',
        'title' => 'Comment Title',
        'subtitle' => '2017-12-10',
        'content' => 'Somme comment text',
        'comments' => [
            [
                'author' => 'Third Author Name',
                'avatar' => 'http://example.com/user3.jpg',
                'title' => 'Comment Title',
                'subtitle' => '2017-12-12',
                'content' => 'Some answer text'
            ],
            [
                'author' => 'Another Author Name',
                'avatar' => 'http://example.com/user4.jpg',
                'title' => 'Comment Title',
                'subtitle' => '2017-12-13',
                'content' => 'Another answer text'
            ],
        ]
    ],
    [
        'author' => 'Second Author Name',
        'avatar' => 'http://example.com/user2.jpg',
        'title' => 'Comment Title',
        'subtitle' => '2017-12-11',
        'content' => 'Some comment text'
    ],
];
$comments = Content::comment('http://example.com/page.html', $commentsArray);



// generate image tag
$image = Content::img('http://example.com/image1.jpg', 'Image title');



// generate share buttons
$shareButtons = Content::share([Content::SHARE_TYPE_VKONTAKTE, Content::SHARE_TYPE_FACEBOOK]);



// generate simple link button
$button = Content::button('Button text', 'http://exmaple.com/page');

// generate disabled link button
$button = Content::button('Button text', 'http://exmaple.com/page',
    null, null, null, false, true);

// generate link button with bold text
$button = Content::button('Button text', 'http://exmaple.com/page',
    null, null, null, true);

// generate link button with configured colors
$button = Content::button('Button text', 'http://exmaple.com/page',
    null, '#cccccc', '#fffff');

// generate phone button
$button = Content::button('Button text', null, '+11231231234');



// generate simple image gallery
$imagesArray = ['http://example.com/image1.jpg', 'http://example.com/image2.jpg'];
$simpleGallery = Content::gallery($imagesArray);

// generate image gallery with title
$galleryWithTitle = Content::gallery($imagesArray, 'Gallery title');



// generate rating block
$rating = Content::rating(3, 5);



// generate accordion block
$accordionArray = [
    ['title' => 'Page title 1', 'text' => 'Text 1'],
    ['title' => 'Page title 2', 'text' => 'Text 2', 'expanded' => true]
];
$accordion = Content::accordion($accordionArray);



// generate block with video from own server
$videoUrl = 'http://example.com/video.mp4';
$imgUrl = 'http://example.com/img.jpg';
$videoCaption = 'Video Caption';
$ownVideo = Content::ownVideo($videoUrl, $videoCaption, Content::OWN_VIDEO_TYPE_MP4, $imgUrl);



// generate block with video from own server
$videoUrl = 'http://example.com/video.mp4';
$options = [
    'width' => 640,
    'height' => 480,
    'frameborder' => 1,
    'allowfullscreen' => 'true',
    'referrerpolicy' => 'unsafe-url',
    'sandbox' => 'allow-forms allow-modals',
    'hd' => 3
];
$externalVideo = Content::externalVideo($videoUrl, $options);



// generate Ad block position element
$adBlockPosition = Content::adBlockPosition('first_ad_place');



// generate slider block
$items = [
    ['url' => 'http://example.com/image1.jpg', 'title' => 'Image title 1', 'link' => ''],
    ['url' => 'http://example.com/image2.jpg', 'title' => 'Image title 2', 'link' => ''],
    ['url' => 'http://example.com/image3.jpg'],
    ['href' => 'http://example.com/page1.html', 'title' => 'Link title 1', 'text' => 'Link text 1']
];
$slider = Content::slider($items);



// generate additional content block
$items = [
    [
        'href' => 'http://example.com/page1.html',
        'title' => 'Item title 1',
        'description' => 'Item description',
        'thumb' => 'http://example/image1.jpg',
        'thumb_position' => Content::ADDITIONAL_CONTENT_THUMB_POSITION_LEFT,
        'thumb_ratio' => Content::ADDITIONAL_CONTENT_THUMB_RATIO_1_1
    ],
    [
        'href' => 'http://example.com/page2.html',
        'title' => 'Item title 2',
    ],
];
$additionalContent = Content::additionalContent($items, 'Title', Content::ADDITIONAL_CONTENT_ORIENTATION_HORIZONTAL);